### ISSUE TITLE
Hide guests or hosts with zero published episodes

### ISSUE THREAD

**Issue by mfessler** [firesidelabs/fireside-features#3]
I have a bunch of episodes in the pipeline, and have added guest info for all of them. However, guests with no published episodes show up too (with 0 episodes duly noted.)

I am aware you can make guests private or public - but since I can schedule an episode to go public at a certain date and time, it would be great to make the associated guest(s) public at the same time. (Besides, we generally drop episodes at midnight…)

Since I'm sure some people will want a guest to be always private or always public, maybe we need a third option for guests: "hide until one of my episodes is public".

**Comment by dan** [comment]
Done and deployed.

**Comment by jamesmontemagno** [comment]
Seems like they still show up for us with 0 episodes... We have public episodes but scheduled for the future. https://www.trinspo.com/guests @dan
